version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - ruby/build-gem:
          context:
            - ergomentum-ruby-gems
          ruby_version: 3.2.0
      - ruby/run-rubocop:
          context:
            - ergomentum-ruby-gems
          ruby_version: 3.2.0
orbs:
  ruby: ergomentum/ruby-orb@1.8.0
