inherit_from: default_shared.yml
require:
  - rubocop-rails

Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true
Rails/AddColumnIndex: # (new in 2.11)
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/Delegate:
  Enabled: false
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: true
Rails/DuplicateAssociation: # new in 2.14
  Enabled: true
Rails/DuplicateScope: # new in 2.14
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/EagerEvaluationLogMessage: # (new in 2.11)
  Enabled: true
Rails/EnvironmentVariableAccess: # (new in 2.10)
  Enabled: false
Rails/ExpandedDateRange: # (new in 2.11)
  Enabled: true
Rails/FilePath:
  EnforcedStyle: arguments
Rails/FindById:
  Enabled: true
Rails/I18nLazyLookup: # new in 2.14
  Enabled: true
Rails/I18nLocaleAssignment: # (new in 2.11)
  Enabled: true
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Rails/RedundantTravelBack: # new in 2.12
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/TimeZoneAssignment: # (new in 2.10)
  Enabled: true
Rails/TransactionExitStatement: # new in 2.14
  Enabled: true
Rails/UnusedIgnoredColumns: # (new in 2.11)
  Enabled: true
Rails/WhereEquals: # (new in 2.9)
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereNot:
  Enabled: true
