---
require:
  - rubocop-performance
AllCops:
  Exclude:
    - vendor/**/*
    - node_modules/**/*
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - gems/**/*_spec.rb
    - spec/**/*
    - config/routes.rb
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Naming/PredicateName:
  Exclude:
    - spec/**/*
  ForbiddenPrefixes:
    - is_
  NamePrefix:
    - is_
    - has_
    - have_
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
Style/CollectionMethods:
  Enabled: true
Style/CommentAnnotation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/Next:
  Enabled: false
Style/OptionHash:
  Enabled: true
  SuspiciousParamNames:
    - options
    - opts
    - args
    - params
    - parameters
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma
Style/TrivialAccessors:
  Enabled: false
