name: Build Ruby Gem
on:
  push:
    branches:
    - main
    paths:
    - lib/ergomentum_rubocop/version.rb
jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and publish gem
      uses: jstastny/publish-gem-to-github@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ergomentum
